# Generated by Django 4.2 on 2024-04-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_cart',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
    ]
